version: '3.8'

services:
  web:
    environment:
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=news_aggregator.settings_docker
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G

  celery_worker:
    environment:
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=news_aggregator.settings_docker
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G

  celery_beat:
    environment:
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=news_aggregator.settings_docker
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  db:
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./backups:/backups
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G

  redis:
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - staticfiles:/staticfiles
      - mediafiles:/mediafiles
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

volumes:
  postgres_data:
  redis_data:
  staticfiles:
  mediafiles: