# Generated by Django 5.1.6 on 2025-05-03 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True, null=True)),
                ("publication_date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="DetectionModelMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100, unique=True)),
                ("accuracy", models.FloatField()),
                ("f1_score", models.FloatField()),
                ("avg_processing_time", models.FloatField()),
                ("avg_memory_usage", models.FloatField()),
                ("parameter_count", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="FakeNewsDetectionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "credibility_score",
                    models.FloatField(help_text="Score from 0 (fake) to 1 (credible)"),
                ),
                (
                    "credibility_category",
                    models.CharField(
                        choices=[
                            ("credible", "Credible"),
                            ("mixed", "Mixed Credibility"),
                            ("fake", "Fake"),
                        ],
                        max_length=20,
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                (
                    "processing_time",
                    models.FloatField(help_text="Processing time in seconds"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detection_result",
                        to="news.article",
                    ),
                ),
            ],
        ),
    ]
