# Generated by Django 5.1.6 on 2025-03-05 22:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleViewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, help_text='When the article was viewed')),
            ],
            options={
                'verbose_name': 'Article View',
                'verbose_name_plural': 'Article Views',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Topic name', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of the topic name', unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the topic', null=True)),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserSavedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True, help_text='When the article was saved')),
                ('notes', models.TextField(blank=True, help_text="User's personal notes about the article", null=True)),
            ],
            options={
                'verbose_name': 'Saved Article',
                'verbose_name_plural': 'Saved Articles',
                'ordering': ['-saved_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-publication_date'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['name'], 'verbose_name': 'News Source', 'verbose_name_plural': 'News Sources'},
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, help_text='Author of the article', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='featured_image_url',
            field=models.URLField(blank=True, help_text="URL to article's featured image", null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='article',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the article has been viewed'),
        ),
        migrations.AddField(
            model_name='source',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the news source', null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the source is currently active'),
        ),
        migrations.AddField(
            model_name='source',
            name='logo_url',
            field=models.URLField(blank=True, help_text="URL to the source's logo image", null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='reliability_score',
            field=models.FloatField(blank=True, help_text='Reliability score (0-10)', null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='bias_score',
            field=models.FloatField(blank=True, help_text='Political bias score (-1.0 left to 1.0 right)', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, help_text='Full content of the article', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=models.DateTimeField(help_text='When the article was published'),
        ),
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.ForeignKey(help_text='Source of the article', on_delete=django.db.models.deletion.CASCADE, to='news.source'),
        ),
        migrations.AlterField(
            model_name='article',
            name='source_article_url',
            field=models.TextField(help_text='Original URL of the article', unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True, help_text='AI-generated summary', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(help_text='Title of the article'),
        ),
        migrations.AlterField(
            model_name='source',
            name='api_endpoint',
            field=models.TextField(blank=True, help_text='API endpoint URL, if available', null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='base_url',
            field=models.TextField(help_text="Base URL of the news source's website"),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(help_text='Name of the news source', max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['name'], name='news_source_name_e1b8b9_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['is_active'], name='news_source_is_acti_ca9cb0_idx'),
        ),
        migrations.AddField(
            model_name='articleviewhistory',
            name='article',
            field=models.ForeignKey(help_text='Viewed article', on_delete=django.db.models.deletion.CASCADE, related_name='view_history', to='news.article'),
        ),
        migrations.AddField(
            model_name='articleviewhistory',
            name='user',
            field=models.ForeignKey(help_text='User who viewed the article', on_delete=django.db.models.deletion.CASCADE, related_name='article_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='topics',
            field=models.ManyToManyField(blank=True, help_text='Topics related to this article', related_name='articles', to='news.topic'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['publication_date'], name='news_articl_publica_e4faf4_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['source'], name='news_articl_source__2047db_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['bias_score'], name='news_articl_bias_sc_1224d1_idx'),
        ),
        migrations.AddField(
            model_name='usersavedarticle',
            name='article',
            field=models.ForeignKey(help_text='Saved article', on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='news.article'),
        ),
        migrations.AddField(
            model_name='usersavedarticle',
            name='user',
            field=models.ForeignKey(help_text='User who saved this article', on_delete=django.db.models.deletion.CASCADE, related_name='saved_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='articleviewhistory',
            index=models.Index(fields=['user', '-viewed_at'], name='news_articl_user_id_08cbcb_idx'),
        ),
        migrations.AddIndex(
            model_name='articleviewhistory',
            index=models.Index(fields=['article', '-viewed_at'], name='news_articl_article_94fcaf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usersavedarticle',
            unique_together={('user', 'article')},
        ),
    ]
