# Generated by Django 5.1.6 on 2025-03-29 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_articleviewhistory_topic_usersavedarticle_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectionModelMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="Model identifier", max_length=100, unique=True
                    ),
                ),
                ("accuracy", models.FloatField(help_text="Overall accuracy score")),
                (
                    "precision",
                    models.FloatField(
                        help_text="Precision score for fake news detection"
                    ),
                ),
                (
                    "recall",
                    models.FloatField(help_text="Recall score for fake news detection"),
                ),
                (
                    "f1_score",
                    models.FloatField(help_text="F1 score for fake news detection"),
                ),
                (
                    "avg_processing_time",
                    models.FloatField(help_text="Average processing time in seconds"),
                ),
                (
                    "avg_memory_usage",
                    models.FloatField(help_text="Average memory usage in MB"),
                ),
                (
                    "parameter_count",
                    models.PositiveIntegerField(
                        help_text="Number of parameters in the model"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Detection Model Metrics",
                "verbose_name_plural": "Detection Model Metrics",
                "ordering": ["-accuracy"],
            },
        ),
        migrations.CreateModel(
            name="FakeNewsDetectionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "credibility_score",
                    models.FloatField(
                        help_text="Score from 0.0 (fake) to 1.0 (credible)"
                    ),
                ),
                (
                    "credibility_category",
                    models.CharField(
                        choices=[
                            ("likely_fake", "Likely Fake"),
                            ("possibly_fake", "Possibly Fake"),
                            ("uncertain", "Uncertain"),
                            ("possibly_credible", "Possibly Credible"),
                            ("likely_credible", "Likely Credible"),
                        ],
                        help_text="Categorization of the credibility assessment",
                        max_length=50,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(help_text="Confidence score from 0 to 1"),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="Name of model used for detection", max_length=100
                    ),
                ),
                (
                    "processing_time",
                    models.FloatField(
                        blank=True, help_text="Processing time in seconds", null=True
                    ),
                ),
                (
                    "memory_usage",
                    models.FloatField(
                        blank=True, help_text="Peak memory usage in MB", null=True
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True, help_text="Explanation of credibility assessment"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Fake News Detection Result",
                "verbose_name_plural": "Fake News Detection Results",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveIndex(
            model_name="article",
            name="news_articl_bias_sc_1224d1_idx",
        ),
        migrations.RemoveField(
            model_name="article",
            name="bias_score",
        ),
        migrations.RemoveField(
            model_name="article",
            name="summary",
        ),
        migrations.AddField(
            model_name="fakenewsdetectionresult",
            name="article",
            field=models.OneToOneField(
                help_text="Article that was analyzed",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fake_news_detection",
                to="news.article",
            ),
        ),
    ]
