# Generated by Django 5.1.6 on 2025-03-05 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0002_articleviewhistory_topic_usersavedarticle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiasDetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bias_score', models.FloatField(help_text='Score from -1.0 (left) to 1.0 (right)')),
                ('bias_category', models.CharField(choices=[('strong_left', 'Strong Left'), ('moderate_left', 'Moderate Left'), ('neutral', 'Neutral/Center'), ('moderate_right', 'Moderate Right'), ('strong_right', 'Strong Right')], max_length=50)),
                ('confidence', models.FloatField(help_text='Confidence score from 0 to 1')),
                ('explanation', models.TextField(blank=True, help_text='Explanation of bias assessment')),
                ('model_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bias_detection_result', to='news.article')),
            ],
            options={
                'verbose_name': 'Bias Detection Result',
                'verbose_name_plural': 'Bias Detection Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SummarizationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField()),
                ('model_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processing_time', models.FloatField(blank=True, help_text='Processing time in seconds', null=True)),
                ('rating', models.FloatField(blank=True, help_text='Quality rating from 0 to 1', null=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summarization_result', to='news.article')),
            ],
            options={
                'verbose_name': 'Summarization Result',
                'verbose_name_plural': 'Summarization Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('summarization', 'Summarization'), ('bias_detection', 'Bias Detection')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_tasks', to='news.article')),
            ],
            options={
                'verbose_name': 'Processing Task',
                'verbose_name_plural': 'Processing Tasks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['article', 'task_type', 'status'], name='processing__article_5db78e_idx')],
            },
        ),
    ]
